### ISSUE TITLE
'make debug' works good but 'make all' does not work

### ISSUE THREAD

**Issue by edy555** [jacklund/btle.js#14]
I found that project which was built with 'make' or 'make all' does not work.
Console output says following error.

> $ node test.js 
> module.js:340
>    throw err;
>          ^
> Error: Cannot find module '../build/Debug/btle.node'

It seems that lib/btle.js explicitly requires Debug/btle.node, but 'make all' rule does not build debug objects.

> var Connection = require('../build/Debug/btle.node').Connection;

If this line is changed to 'Release' this error doesn't occur,
however if project was built with 'make debug' it becomes to be fail.

It should be written in README that project must be built with 'make debug',
or should omit the rule of 'all' from Makefile temporarily, I think.

**Comment by jacklund** [comment]
Yeah, I kind of knew about this problem. The issue is that you have to explicitly specify "Release" or "Debug" in the javascript file that accesses the C++ module. Right now I've been building debug because I'm still at the point where I might need to drop into gdb to debug a seg fault, but hopefully soon I won't need to.

I'll investigate and see if there is a way to do this better.

Thanks.

-Jack

**Comment by jacklund** [comment]
I don't think there's any way to programmatically fix this. The only thing I can suggest is that if you do a 'make', you change the 'Debug' in lib/btle.js to 'Release', and everything should work. Once I'm confident of the stability of this code base, I'll switch the default to be Release.
