### ISSUE TITLE
Bluetooth listener

### ISSUE THREAD

**Issue by jonathanwiesel** [jacklund/btle.js#16]
Hello,
I would like the RPi to listen for connecting devices so they can send data to it. I haven't worked with Bluetooth before so I'm kind of lost. 

If I understand the usage example correctly it start with the server connecting to the device. In my case I would like the server to listen for connections and be discoverable so other devices can see it, connect to it and send data to it.

If you could help me with this I would appreciate it, there's not much info about bluetooth and RPi interaction (apart from direct shell connection).

**Comment by jacklund** [comment]
I'm actually working on adding the functionality to allow bile.js to do just that - right now it can only act in "central" mode, where it can connect to peripherals. I'm working on the advertising portion right now. Once I get that working, I'll add the ability to listen for incoming connection requests, and be able to define and publish services.

Don't really have an ETA for it, since I'm working on this in my spare time, but hopefully it won't be too long.
